name: Deploy Client

on:
  push:
    branches: [main]
    # 仅当 client/ 目录有变更时触发
    paths:
      - 'letschat-front/**'

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Client
        working-directory: ./letschat-front  # 指定客户端目录
        run: |
          npm install
          npm run build
          
      - name: Install rsync and SSH Key Setup
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # 将远程服务器的主机密钥添加到已知主机（避免首次连接确认）
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
      - name: transfer to Cloud
        run: |
          rsync -avz --delete \
            --exclude="node_modules" \
            ./letschat-front/dist \
            root@$SERVER_IP:/home/letschat-front/
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
      - name: Deploy to docker cloud
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 进入项目
            cd /home/letschat-front
            # 停止容器 删除容器 删除镜像 构建镜像 启动容器
            docker stop letschatfront1
            docker rm letschatfront1
            docker rmi letschatfront1
            docker build -t letschatfront1 .
            docker run -d -p 80:80 --name letschatfront1 letschatfront1
            
