name: Deploy Client

on:
  push:
    branches: [main]
    # 仅当 client/ 目录有变更时触发
    paths:
      - 'letschat-front/**'

jobs:
  build-and-deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and Build Client
        working-directory: ./letschat-front  # 指定客户端目录
        run: |
          npm install
          npm run build
          
      - name: Install rsync and SSH Key Setup
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # 将远程服务器的主机密钥添加到已知主机（避免首次连接确认）
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
      - name: Deploy to Cloud
        run: |
          rsync -avz \
            --exclude="node_modules" \
            ./letschat-front/dist/ \
            root@$SERVER_IP:/home/
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
      # - name: Deploy to Cloud
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SERVER_IP }}
      #     username: root
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       # 调试：列出构建产物是否存在
      #       # ls -la ./letschat-front/dist/
      #       # 同步文件
      #       rsync -avz ./letschat-front/dist/ root@${{ secrets.SERVER_IP }}:/home/
